#import <PEGKit/PKParser.h>

enum {
    GHERKINPARSER_TOKEN_KIND_EXAMPLE = 14,
    GHERKINPARSER_TOKEN_KIND_COLON,
    GHERKINPARSER_TOKEN_KIND_FEATURE,
    GHERKINPARSER_TOKEN_KIND_LT_SYM,
    GHERKINPARSER_TOKEN_KIND_SCENARIO,
    GHERKINPARSER_TOKEN_KIND_GIVEN,
    GHERKINPARSER_TOKEN_KIND_AND,
    GHERKINPARSER_TOKEN_KIND_OUTLINE,
    GHERKINPARSER_TOKEN_KIND_GT_SYM,
    GHERKINPARSER_TOKEN_KIND_WHEN,
    GHERKINPARSER_TOKEN_KIND__R,
    GHERKINPARSER_TOKEN_KIND_THEN,
    GHERKINPARSER_TOKEN_KIND_PIPE,
    GHERKINPARSER_TOKEN_KIND__N,
    GHERKINPARSER_TOKEN_KIND_BACKGROUND,
    GHERKINPARSER_TOKEN_KIND_AT,
};

@interface GherkinParser : PKParser
        

- (void)push:(id)object;
- (id)pop;
- (id)peek;


@end

